// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// prod_cpp
arma::mat prod_cpp(const arma::mat& Z);
RcppExport SEXP EstHer_prod_cpp(SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    __result = Rcpp::wrap(prod_cpp(Z));
    return __result;
END_RCPP
}
